controller_list:
  - name: rmf_obelix
    action_ns: follow_joint_trajectory
    type: MultiDofFollowJointTrajectory
    default: true
    joints:
      - virtual_joint/trans_x
      - virtual_joint/trans_y
      - virtual_joint/trans_z
      - virtual_joint/rot_x
      - virtual_joint/rot_y
      - virtual_joint/rot_z
      - virtual_joint/rot_w